# 一、张量的简介

## 1、Variable

Variable是torch.autograd中的数据类型，主要用于封装Tensor，进行自动求导

- `data`：被包装的Tensor
- `grad`：data的梯度
- `grad_fn`：创建Tensor的Function，是自动求导的关键
- `requires_grad`：指示是否需要梯度
- `is_leaf`：指示是否是叶子结点（张量）

## 2、Tensor

pytorch0.4.0版开始，Variable并入Tensor

- `dtype`：张量的数据类型，如`torch.FloatTensor`，`torch.cuda.FloatTensor`
- `shape`：张量的形状，如`(64, 3, 224, 224)`
- `device`：张量所在设备，GPU/CPU，是加速关键

# 二、张量的创建

## 1、直接创建

### 1.1 `torch.tensor()`

In [224]:
# torch.tensor(
#     data,
#     dtype=None,
#     device=None,
#     requires_grad=False,
#     pin_memory=False
# )

功能：从data创建tensor

- `data`：数据，可以是list，numpy
- `dtype`：数据类型，默认与data一致
- `device`：所在设备，cuda/cpu
- `requires_grad`：是否需要梯度
- `pin_memory`：是否存于锁页内存

In [225]:
import numpy as np
import torch

In [226]:
flag = True
if flag:
    arr = np.ones((3, 3))
    print("数据类型：", arr.dtype)

    t = torch.tensor(arr)
    print(t)

数据类型： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### 1.2 `torch.from_numpy(ndarray)`

功能：从numpy创建tensor

**注意事项**：
1. 从torch.from_numpy创建的tensor于原ndarray共享内存，当修改其中一个的数据，另一个也会被修改

In [227]:
flag = True
if flag:
    arr1 = np.array([[1, 2, 3], [4, 5, 6]])
    t = torch.from_numpy(arr1)
    print("array：", arr1)
    print("tensor：", t)

    print('-'*100)

    arr1[0, 0] = 0
    print("array：", arr1)
    print("tensor：", t)

    print('-'*100)

    t[0, 0] = -1
    print("array：", arr1)
    print("tensor：", t)

array： [[1 2 3]
 [4 5 6]]
tensor： tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
----------------------------------------------------------------------------------------------------
array： [[0 2 3]
 [4 5 6]]
tensor： tensor([[0, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
----------------------------------------------------------------------------------------------------
array： [[-1  2  3]
 [ 4  5  6]]
tensor： tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


## 2、依据数值创建

### 2.1 `torch.zeros()`

In [228]:
# torch.zeros(
#     *size,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：依size创建全0张量

- `size`：张量的形状，如(3, 3)，(3, 224, 224)
- `out`：输出的张量
- `layout`：内存中布局形式，有strided，sparse_coo等
- `device`：所在设备，gpu/cpu
- `requires_grad`：是否需要梯度

In [229]:
flag = True
if flag:
    t2 = torch.tensor([1])
    t = torch.zeros((3, 3), out=t2)

    print("t：", t)
    print("t2：", t2)
    print(id(t), id(t2), id(t) == id(t2))

t： tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
t2： tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
1266643551632 1266643551632 True


### 2.2 `torch.zeros_like()`

In [230]:
# torch.zeros_like(
#     input,
#     dtype=None,
#     layout=None,
#     device=None,
#     requires_grad=False
# )

功能：依input形状创建全0张量

- `input`：创建与input同形状的全0张量
- `dtype`：数据类型
- `layout`：内存中布局形式

### 2.3 `torch.ones()`

In [231]:
# torch.ones(
#     *size,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

### 2.4 `torch.ones_like()`

In [232]:
# torch.ones_like(
#     input,
#     dtype=None,
#     layout=None,
#     device=None,
#     requires_grad=False
# )

功能：依input形状创建全1张量
- `size`：张量的形状
- `dtype`：数据类型
- `layout`：内存中布局形式
- `device`：所在设备，cpu/gpu
- `requires_grad`：是否需要梯度

### 2.5 `torch.full()`

In [233]:
# torch.fu1l(
#     *size,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

In [234]:
flag = True
if flag:
    t = torch.full((3, 3), 1)
    print(t)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


### 2.6 `torch.full_like()`

In [235]:
# torch.full_like(
#     input,
#     fill_value,
#     dtype=None,
#     layout=None,
#     device=None,
#     requires_grad=False
# )

功能：依input形状创建全0张量
- `size`：张量的形状
- `fill_value`：张量的值

### 2.7 `torch.arange()`

In [236]:
# torch.arange(
#     start=0,
#     end,
#     step=1,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：创建等差的1维张量

注意：数值区间为[start, end)
- `start`：数列起始值
- `end`：数列“结束值”
- `step`：数列公差，默认为1

In [237]:
flag = True
if flag:
    t = torch.arange(2, 10, 2)
    print(t)

tensor([2, 4, 6, 8])


### 2.8 `torch.linspace()`

In [238]:
# torch.linspace(
#     start,
#     end,
#     steps,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：创建均分的1维张量

注意：数值区间为[start, end]
- `start`：数列起始值
- `end`：数列结束值
- `steps`：数列长度

In [239]:
flag = True
if flag:
    t = torch.linspace(2, 10, 6)
    print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


### 2.9 `torch.logspace()`

In [240]:
# torch.logspace(
#     start,
#     end,
#     steps,
#     base=10.0,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：创建对数均分的1维张量

注意：长度为steps，底为base
- `start`：数列起始值
- `end`：数列结束值
- `steps`：数列长度
- `base`：对数函数的底，默认为10

### 2.10 `torch.eye()`

In [241]:
# torch.eye(
#     n,
#     m=None,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：创建单位对角矩阵（2维张量）
注意：默认为方阵
- `n`：矩阵行数
- `m`：矩阵列数

## 3、依概率分布创建张量

### 3.1 `torch.normal()`

In [242]:
# torch.normal(
#     mean=0.0,
#     std=1.0,
#     size=(2, 3),
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：生成正态分布（高斯分布）
- `mean`：均值
- `std`：标准差

In [243]:
flag = True
if flag:
    # （1）mean：张量， std：张量
    mean = torch.arange(1, 5, dtype=torch.float)
    std = torch.arange(1, 5, dtype=torch.float)
    t_normal = torch.normal(mean, std)
    print("mean：", mean)
    print("std：", std)
    print("t_normal：", t_normal)
    print('-'*100)

    # （2）mean：标量， std：标量
    t_normal1 = torch.normal(0., 1., size=(4,))
    print("t_normal1：", t_normal1)
    print('-'*100)

    # （3）mean：标量， std：张量
    mean = 0
    std = torch.arange(1, 5, dtype=torch.float)
    t_normal3 = torch.normal(mean, std)
    print("mean：", mean)
    print("std：", std)
    print("t_normal3：", t_normal3)
    print('-'*100)
    

    # （4）mean：张量， std：标量
    mean = torch.arange(1, 5, dtype=torch.float)
    std = 1
    t_normal2 = torch.normal(mean, std)
    print("mean：", mean)
    print("std：", std)
    print("t_normal2：", t_normal2)


mean： tensor([1., 2., 3., 4.])
std： tensor([1., 2., 3., 4.])
t_normal： tensor([0.4311, 4.0635, 3.1900, 1.2404])
----------------------------------------------------------------------------------------------------
t_normal1： tensor([-0.1281, -1.9552,  1.5685,  0.5102])
----------------------------------------------------------------------------------------------------
mean： 0
std： tensor([1., 2., 3., 4.])
t_normal3： tensor([ 1.1218,  3.5642, -4.7367,  2.7311])
----------------------------------------------------------------------------------------------------
mean： tensor([1., 2., 3., 4.])
std： 1
t_normal2： tensor([1.1351, 2.5704, 3.0849, 6.0902])


### 3.2 `torch.randn()`

In [244]:
# torch.randn(
#     *size,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

### 3.3 `torch.randn_like()`

In [245]:
# torch.randn_like(
#     input,
#     dtype=None,
#     layout=None,
#     device=None,
#     requires_grad=False
# )

功能：生成标准**正态分布**
- `size`：张量的形状

### 3.4 `torch.rand()`

In [246]:
# torch.rand(
#     *size,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

### 3.5 `torch.rand_like()`

In [247]:
# torch.rand_like(
#     input,
#     dtype=None,
#     layout=None,
#     device=None,
#     requires_grad=False   
# )

功能：在区间[0, 1)上，生成**均匀分布**

### 3.6 `torch.randint()`

In [248]:
# torch.randint(
#     low=0,
#     high=10,
#     size=(2, 3),
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

### 3.7 `torch.randint_like()`

In [249]:
# torch.randint_like(
#     input,
#     low=0,
#     high=10,
#     dtype=None,
#     layout=None,
#     device=None,
#     requires_grad=False
# )

功能：在区间[low, high)生成整数**均匀分布**
- `size`：张量的形状

### 3.8 `torch.randperm()`

In [250]:
# torch.randperm(
#     n,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：生成从0到n-1的随机排列
- `n`：张量的长度

### 3.9 `torch.bernoulli()`

In [251]:
# torch.bernoulli(
#     input,
#     generator=None,
#     out=None,
#     dtype=None,
#     layout=torch.strided,
#     device=None,
#     requires_grad=False
# )

功能：以input为概率，生成伯努力分布（0-1分布，两点分布）
- `input`：概率值