In [783]:
import torch

# 一、张量的操作

## 1、张量的拼接与切分

### 1.1 `torch.cat()`

In [784]:
# torch.cat(
#     tensors,
#     dim=0,
#     out=None
# )

功能：将张量按维度dim进行拼接
- `tensors`：张量序列
- `dim`：要拼接的维度

In [785]:
if True:
    t = torch.ones((2, 3))
    t0 = torch.cat([t, t], dim=0)
    t1 = torch.cat([t, t], dim=1)
    t2 = torch.cat([t, t, t], dim=1)
    print("t：", t, t.shape)
    print('-'*100)
    print("t0：", t0, t0.shape)
    print('-'*100)
    print("t1：", t1, t1.shape)
    print('-'*100)
    print("t2：", t2, t2.shape)

t： tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])
----------------------------------------------------------------------------------------------------
t0： tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])
----------------------------------------------------------------------------------------------------
t1： tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) torch.Size([2, 6])
----------------------------------------------------------------------------------------------------
t2： tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]) torch.Size([2, 9])


### 1.2 `torch.stack()`

In [786]:
# torch.stack(
#     tensors,
#     dim=0,
#     out=None
# )

功能：在新创建的维度dim上进行拼接
- `tensors`：张量序列
- `dim`：要拼接的维度

In [787]:
if True:
    t = torch.ones((2, 3))
    t0 = torch.stack([t, t], dim=0)
    t1 = torch.stack([t, t], dim=1)
    t2 = torch.stack([t, t, t], dim=0)
    print("t：", t, t.shape)
    print('-'*100)
    print("t0：", t0, t0.shape)
    print('-'*100)
    print("t1：", t1, t1.shape)
    print('-'*100)
    print("t2：", t2, t2.shape)

t： tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])
----------------------------------------------------------------------------------------------------
t0： tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])
----------------------------------------------------------------------------------------------------
t1： tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])
----------------------------------------------------------------------------------------------------
t2： tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([3, 2, 3])


### 1.3 `torch.chunk()`

In [788]:
# torch.chunk(
#     tensor,
#     chunks,
#     dim=0,
#     out=None
# )

功能：将张量按维度dim进行平均切分
返回值：张量列表
注意：若不能除整，最后一份张量小于其他张量
- `input`：要切分的张量
- `chunks`：要切分的份数
- `dim`：要切分的维度

In [789]:
if True:
    a = torch.ones((2, 5))
    list_of_tensors = torch.chunk(a, dim=1, chunks=2)

    for idx, t in enumerate(list_of_tensors):
        print("t{}：".format(idx), t, t.shape)

t0： tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])
t1： tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])


### 1.4 `torch.split()`

In [790]:
# torch.split(
#     tensor,
#     split_size_or_sections,
#     dim=0,
#     out=None
# )

功能：将张量按维度dim进行切分
返回值：张量列表
- `tensor`：要切分的张量
- `split_size_or_sections`：int，表示每一份的长度；list，表示按list元素切分
- `dim`：要切分的维度

In [791]:
if True:
    t = torch.ones((2, 5))
    list_of_tensors = torch.split(t, 2, dim=1)
    for idx, t in enumerate(list_of_tensors):
        print("t{}：".format(idx), t, t.shape)

    print('-'*100)

    t = torch.ones((2, 5))
    list_of_tensors1 = torch.split(t, [2, 1, 2], dim=1)
    for idx, t in enumerate(list_of_tensors1):
        print("t{}：".format(idx), t, t.shape)

t0： tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
t1： tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
t2： tensor([[1.],
        [1.]]) torch.Size([2, 1])
----------------------------------------------------------------------------------------------------
t0： tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
t1： tensor([[1.],
        [1.]]) torch.Size([2, 1])
t2： tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])


## 2、张量索引

### 2.1 `torch.index_select()`

In [792]:
# torch.index_select(
#     input,
#     dim,
#     index,
#     out=None
# )

功能：在维度dim上，按index索引数据
返回值：依index索引数据拼接的张量
- `input`：要索引的张量
- `dim`：要索引的维度
- `index`：要索引数据的序号

In [793]:
if True:
    t = torch.randint(0, 9, size=(3, 3))
    idx = torch.tensor([0, 2], dtype=torch.long) # 此处不可以用 float 类型的索引
    t_select = torch.index_select(t, dim=0, index=idx)
    print("t：", t, t.shape)
    print('-'*100)
    print("t_select：", t_select, t_select.shape)

t： tensor([[1, 5, 1],
        [0, 4, 5],
        [0, 2, 4]]) torch.Size([3, 3])
----------------------------------------------------------------------------------------------------
t_select： tensor([[1, 5, 1],
        [0, 2, 4]]) torch.Size([2, 3])


### 2.2 `torch.masked_select()`

In [794]:
# torch.masked_select(
#     input,
#     mask,
#     out=None
# )

功能：按mask中的True进行索引
返回值：一维张量
- `input`：要索引的张量
- `mask`：与input同形状的布尔类型张量

In [795]:
if True:
    t = torch.randint(0, 9, size=(3, 3))
    mask = t.ge(5) # 大于等于 5 的元素为 True
    t_select = torch.masked_select(t, mask)
    print("t：", t, t.shape)
    print('-'*100)
    print("mask：", mask, mask.shape)
    print('-'*100)
    print("t_select：", t_select, t_select.shape)

t： tensor([[0, 5, 4],
        [6, 0, 3],
        [4, 0, 6]]) torch.Size([3, 3])
----------------------------------------------------------------------------------------------------
mask： tensor([[False,  True, False],
        [ True, False, False],
        [False, False,  True]]) torch.Size([3, 3])
----------------------------------------------------------------------------------------------------
t_select： tensor([5, 6, 6]) torch.Size([3])


## 3、张量的变换

### 3.1 `torch.reshape()`

In [796]:
# torch.reshape(
#     input,
#     shape,
#     *,  # 位置参数之后的参数必须使用关键字参数传入
#     out=None
# )

功能：变换张量形状
注意：当张量在内存中是连续时，新张量与input共享内存数据
- `input`：要变换的张量
- `shape`：新张量的形状

In [797]:
if True:
    t = torch.randperm(8)
    t_reshape = torch.reshape(t, (2, 4))
    print("t：", t, t.shape)
    print('-'*100)
    print("t_reshape：", t_reshape, t_reshape.shape)
    print('-'*100)

    t[0] = 100
    print("t：", t, t.shape, id(t.data))
    print('-'*100)
    print("t_reshape：", t_reshape, t_reshape.shape, id(t_reshape.data))

t： tensor([0, 6, 3, 1, 5, 2, 7, 4]) torch.Size([8])
----------------------------------------------------------------------------------------------------
t_reshape： tensor([[0, 6, 3, 1],
        [5, 2, 7, 4]]) torch.Size([2, 4])
----------------------------------------------------------------------------------------------------
t： tensor([100,   6,   3,   1,   5,   2,   7,   4]) torch.Size([8]) 1356502593904
----------------------------------------------------------------------------------------------------
t_reshape： tensor([[100,   6,   3,   1],
        [  5,   2,   7,   4]]) torch.Size([2, 4]) 1356502593904


### 3.2 `torch.transpose()`

In [798]:
# torch.transpose(
#     input,
#     dim0,
#     dim1,
#     out=None
# )

功能：交换张量的两个维度
- `input`：要交换的张量
- `dim0`：要交换的维度
- `dim1`：要交换的维度

In [799]:
if True:
    t = torch.rand((2, 3, 4))
    t_transpose = torch.transpose(t, dim0=1, dim1=2)
    print("t：", t, t.shape)
    print('-'*100)
    print("t_transpose：", t_transpose, t_transpose.shape)

t： tensor([[[0.3400, 0.7517, 0.7816, 0.1732],
         [0.5583, 0.7805, 0.5468, 0.7307],
         [0.6938, 0.0920, 0.8110, 0.3886]],

        [[0.0261, 0.6032, 0.6139, 0.1511],
         [0.2064, 0.6391, 0.8214, 0.3930],
         [0.6488, 0.6961, 0.9376, 0.7571]]]) torch.Size([2, 3, 4])
----------------------------------------------------------------------------------------------------
t_transpose： tensor([[[0.3400, 0.5583, 0.6938],
         [0.7517, 0.7805, 0.0920],
         [0.7816, 0.5468, 0.8110],
         [0.1732, 0.7307, 0.3886]],

        [[0.0261, 0.2064, 0.6488],
         [0.6032, 0.6391, 0.6961],
         [0.6139, 0.8214, 0.9376],
         [0.1511, 0.3930, 0.7571]]]) torch.Size([2, 4, 3])


### 3.3 `torch.t()`

In [800]:
# torch.t(
#     input,
#     out=None
# )

功能：2维张量转置，对矩阵而言，等价于 `torch.transpose(innput, o, 1)`

### 3.4 `torch.squeeze()`

In [801]:
# torch.squeeze(
#     input,
#     dim=None,
#     out=None
# )

功能：**压缩**长度为1的维度（轴）
- `dim`：若为None，移除所有长度为1的轴；若为指定维度，当且仅当该轴为1时，可以被移除

In [802]:
if True:
    t = torch.rand((2, 1, 3, 1, 4))
    t_squeeze = torch.squeeze(t)
    print("t：", t, t.shape)
    print('-'*100)
    print("t_squeeze：", t_squeeze, t_squeeze.shape)
    print('-'*100)

    t_squeeze1 = torch.squeeze(t, dim=0)
    print("t_squeeze1：", t_squeeze1, t_squeeze1.shape)
    print('-'*100)

    t_squeeze2 = torch.squeeze(t, dim=1)
    print("t_squeeze2：", t_squeeze2, t_squeeze2.shape)


t： tensor([[[[[0.0896, 0.7389, 0.0146, 0.0997]],

          [[0.4104, 0.4475, 0.6695, 0.3066]],

          [[0.9278, 0.1612, 0.3076, 0.9938]]]],



        [[[[0.1588, 0.6286, 0.8556, 0.9246]],

          [[0.0914, 0.5131, 0.2280, 0.8002]],

          [[0.7309, 0.2737, 0.8343, 0.4437]]]]]) torch.Size([2, 1, 3, 1, 4])
----------------------------------------------------------------------------------------------------
t_squeeze： tensor([[[0.0896, 0.7389, 0.0146, 0.0997],
         [0.4104, 0.4475, 0.6695, 0.3066],
         [0.9278, 0.1612, 0.3076, 0.9938]],

        [[0.1588, 0.6286, 0.8556, 0.9246],
         [0.0914, 0.5131, 0.2280, 0.8002],
         [0.7309, 0.2737, 0.8343, 0.4437]]]) torch.Size([2, 3, 4])
----------------------------------------------------------------------------------------------------
t_squeeze1： tensor([[[[[0.0896, 0.7389, 0.0146, 0.0997]],

          [[0.4104, 0.4475, 0.6695, 0.3066]],

          [[0.9278, 0.1612, 0.3076, 0.9938]]]],



        [[[[0.1588, 0.6286,

### 3.5 `torch.unsqueeze()`

In [803]:
# torch.unsqueeze(
#     input,
#     dim,
#     out=None
# )

功能：依据dim**扩展**维度
- `dim`：扩展的维度

# 二、张量的数学运算

## 2.1 加减乘除

### 2.1.1 `torch.add()`

功能：对两个张量进行逐元素相加，并返回一个新的张量作为结果

In [804]:
if True:
    # （1）基本用法
    a = torch.tensor([1, 2, 3])
    b = torch.tensor([4, 5, 6])
    result = torch.add(a, b)
    print(result)
    print('-'*100)

    # （2）带权重的加法
    result1 = torch.add(a, b, alpha=2)
    print(result1)
    print('-'*100)

    # （3）广播机制
    a = torch.tensor([[1, 2], [3, 4]])
    b = torch.tensor([10, 20])
    result2 = torch.add(a, b)
    print(result2)

tensor([5, 7, 9])
----------------------------------------------------------------------------------------------------
tensor([ 9, 12, 15])
----------------------------------------------------------------------------------------------------
tensor([[11, 22],
        [13, 24]])


### 2.1.2 `torch.addcdiv()`

功能：将一个张量与两个其他张量按元素相除的结果相加，并支持通过一个标量对除法结果进行缩放

计算公式：$output = input + value * (tensor1 / tensor2)$

In [805]:
if True:
    input = torch.tensor([1.0, 2.0, 3.0])
    tensor1 = torch.tensor([4.0, 5.0, 6.0])
    tensor2 = torch.tensor([2.0, 2.0, 2.0])

    result = torch.addcdiv(input, tensor1, tensor2, value=0.5)
    print(result)

tensor([2.0000, 3.2500, 4.5000])


### 2.1.3 `torch.addcmul()`

功能：将一个张量与两个其他张量按元素相乘的结果相加，并支持通过一个标量对乘法结果进行缩放

计算公式：$output = input + value * (tensor1 * tensor2)$

In [806]:
if True:
    input = torch.tensor([1.0, 2.0, 3.0])
    tensor1 = torch.tensor([4.0, 5.0, 6.0])
    tensor2 = torch.tensor([2.0, 2.0, 2.0])

    result = torch.addcmul(input, tensor1, tensor2, value=0.5)
    print(result)

tensor([5., 7., 9.])


### 2.1.4 `torch.sub()`

功能：对两个张量进行逐元素相减，并返回一个新的张量作为结果

In [807]:
if True:
    # （1）基本用法
    a = torch.tensor([5, 7, 9])
    b = torch.tensor([1, 2, 3])
    result = torch.sub(a, b)
    print(result)
    print('-'*100)

    # （2）带权重的减法
    result1 = torch.sub(a, b, alpha=2)
    print(result1)
    print('-'*100)

    # （3）广播机制
    c = torch.tensor([[5, 7, 9], [10, 12, 14]])
    d = torch.tensor([1, 2, 3])
    result3 = torch.sub(a, b)
    print(result3)

tensor([4, 5, 6])
----------------------------------------------------------------------------------------------------
tensor([3, 3, 3])
----------------------------------------------------------------------------------------------------
tensor([4, 5, 6])


### 2.1.5 `torch.div()`

功能：对两个张量进行逐元素相除，并返回一个新的张量作为结果

In [808]:
if True:
    # （1）基本用法
    a = torch.tensor([10.0, 20.0, 30.0])
    b = torch.tensor([2.0, 4.0, 5.0])
    # 张量与张量相除
    result = torch.div(a, b)
    print(result)
    print('-'*100)

    # 张量与标量相除
    result1 = torch.div(a, 2.0)
    print(result1)
    print('-'*100)

    # （2）广播机制
    c = torch.tensor([[10.0, 20.0, 30.0], [40.0, 50.0, 60.0]])
    d = torch.tensor([2.0, 4.0, 5.0])
    result2 = torch.div(c, d)
    print(result2)

tensor([5., 5., 6.])
----------------------------------------------------------------------------------------------------
tensor([ 5., 10., 15.])
----------------------------------------------------------------------------------------------------
tensor([[ 5.0000,  5.0000,  6.0000],
        [20.0000, 12.5000, 12.0000]])


### 2.1.6 `torch.mul()`

功能：对两个张量的对应元素进行相乘操作，并返回一个新的张量作为结果

In [809]:
if True:
    # （1）基本用法
    a = torch.tensor([1, 2, 3])
    b = torch.tensor([4, 5, 6])
    # 张量与张量相乘
    result = torch.mul(a, b)
    print(result)
    print('-'*100)

    # 张量与标量相乘
    result1 = torch.mul(a, 2)
    print(result1)
    print('-'*100)

    # （2）广播机制
    c = torch.tensor([[1, 2, 3], [4, 5, 6]])
    d = torch.tensor([2, 3, 4])
    result2 = torch.mul(c, d)
    print(result2)

tensor([ 4, 10, 18])
----------------------------------------------------------------------------------------------------
tensor([2, 4, 6])
----------------------------------------------------------------------------------------------------
tensor([[ 2,  6, 12],
        [ 8, 15, 24]])


## 2.2 对数、指数、幂函数

### 2.2.1 `torch.log(input, out=None)`

功能：对输入张量的每个元素执行逐元素操作，并返回一个新的张量作为结果

In [810]:
if True:
    # （1）基本用法
    a = torch.tensor([1.0, 2.7183, 10.0])

    result = torch.log(a)
    print(result)
    print('-'*100)

    # （2）使用out参数
    output = torch.empty(3)
    torch.log(a, out=output)
    print(output)

tensor([0.0000, 1.0000, 2.3026])
----------------------------------------------------------------------------------------------------
tensor([0.0000, 1.0000, 2.3026])


### 2.2.2 `torch.log10(input, out=None)`

### 2.2.3 `torch.log2(input, out=None)`

### 2.2.4 `torch.exp(input, out=None)`

### 2.2.5 `torch.pow()`

## 2.3 三角函数

### 2.3.1 `torch.abs(input, out=None)`

### 2.3.2 `torch.acos(input, out=None)`

### 2.3.3 `torch.cosh(input, out=None)`

### 2.3.4 `torch.cos(input, out=None)`

### 2.3.5 `torch.asin(input, out=None)`

### 2.3.6 `torch.atan(input, out=None)`

### 2.3.7 `torch.atan2(input, other, out=None)`

# 三、线性回归