# 一、张量的简介

## 1、Variable

Variable是torch.autograd中的数据类型，主要用于封装Tensor，进行自动求导

- `data`：被包装的Tensor
- `grad`：data的梯度
- `grad_fn`：创建Tensor的Function，是自动求导的关键
- `requires_grad`：指示是否需要梯度
- `is_leaf`：指示是否是叶子结点（张量）

## 2、Tensor

pytorch0.4.0版开始，Variable并入Tensor

- `dtype`：张量的数据类型，如`torch.FloatTensor`，`torch.cuda.FloatTensor`
- `shape`：张量的形状，如`(64, 3, 224, 224)`
- `device`：张量所在设备，GPU/CPU，是加速关键

# 二、张量的创建

## 1、直接创建

### 1.1 `torch.tensor()`

功能：从data创建tensor

- `data`：数据，可以是list，numpy
- `dtype`：数据类型，默认与data一致
- `device`：所在设备，cuda/cpu
- `requires_grad`：是否需要梯度
- `pin_memory`：是否存于锁页内存

In [29]:
import numpy as np
import torch

In [30]:
flag = True
if flag:
    arr = np.ones((3, 3))
    print("数据类型：", arr.dtype)

    t = torch.tensor(arr)
    print(t)

数据类型： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### 1.2 `torch.from_numpy(ndarray)`

功能：从numpy创建tensor

**注意事项**：
1. 从torch.from_numpy创建的tensor于原ndarray共享内存，当修改其中一个的数据，另一个也会被修改

In [31]:
flag = True
if flag:
    arr1 = np.array([[1, 2, 3], [4, 5, 6]])
    t = torch.from_numpy(arr1)
    print("array：", arr1)
    print("tensor：", t)

    print('-'*100)

    arr1[0, 0] = 0
    print("array：", arr1)
    print("tensor：", t)

    print('-'*100)

    t[0, 0] = -1
    print("array：", arr1)
    print("tensor：", t)

array： [[1 2 3]
 [4 5 6]]
tensor： tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
----------------------------------------------------------------------------------------------------
array： [[0 2 3]
 [4 5 6]]
tensor： tensor([[0, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
----------------------------------------------------------------------------------------------------
array： [[-1  2  3]
 [ 4  5  6]]
tensor： tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


## 2、依据数值创建

### 2.1 `torch.zeros()`

功能：依size创建全0张量

- `size`：张量的形状，如(3, 3)，(3, 224, 224)
- `out`：输出的张量
- `layout`：内存中布局形式，有strided，sparse_coo等
- `device`：所在设备，gpu/cpu
- `requires_grad`：是否需要梯度

In [32]:
flag = True
if flag:
    t2 = torch.tensor([1])
    t = torch.zeros((3, 3), out=t2)

    print("t：", t)
    print("t2：", t2)
    print(id(t), id(t2), id(t) == id(t2))

t： tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
t2： tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
2002125950224 2002125950224 True
